# Generated by Django 5.1 on 2024-08-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestName', models.CharField(max_length=100)),
                ('UOMID', models.IntegerField()),
                ('CreatedDt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['TestName'],
            },
        ),
    ]
