# Generated by Django 5.1 on 2024-08-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaticData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UOMName', models.CharField(max_length=100)),
                ('CreatedDt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['UOMName'],
            },
        ),
        migrations.RemoveField(
            model_name='test',
            name='UOMID',
        ),
    ]
