# Generated by Django 5.1 on 2024-08-30 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaticData', '0002_uom_remove_test_uomid'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='UOMID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='StaticData.uom'),
            preserve_default=False,
        ),
    ]
