# Generated by Django 5.1 on 2024-08-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaticData', '0003_test_uomid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaterialName', models.CharField(max_length=100)),
                ('MaterialDescription', models.CharField(max_length=150)),
                ('CreatedDt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['MaterialName'],
            },
        ),
    ]
