# Generated by Django 5.1 on 2024-08-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaticData', '0005_sampletype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusName', models.CharField(max_length=100)),
                ('Type', models.IntegerField()),
                ('CreatedDt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['StatusName'],
            },
        ),
    ]
