# Generated by Django 5.1 on 2024-09-12 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaticData', '0007_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StaticData.event')),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StaticData.test')),
            ],
        ),
    ]
