# Generated by Django 5.1 on 2024-08-30 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StaticData', '0006_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identifier', models.CharField(max_length=100)),
                ('CreatedDt', models.DateTimeField(auto_now_add=True)),
                ('SampleTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StaticData.sampletype')),
            ],
            options={
                'ordering': ['-CreatedDt'],
            },
        ),
    ]
