# Generated by Django 5.1 on 2024-08-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Samples', '0002_sample_materialid_sample_sampledt_sample_statusid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='Priority',
            field=models.BooleanField(default=False),
        ),
    ]
