# Generated by Django 5.1 on 2024-09-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Samples', '0003_sample_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='MaterialID',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='StatusID',
        ),
        migrations.AlterField(
            model_name='sample',
            name='SampleTypeID',
            field=models.IntegerField(),
        ),
    ]
