# Generated by Django 5.1 on 2024-09-02 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Samples', '0004_remove_sample_materialid_remove_sample_statusid_and_more'),
        ('StaticData', '0006_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='SampleTypeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StaticData.sampletype'),
        ),
    ]
