# Generated by Django 5.1 on 2024-09-02 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Samples', '0005_alter_sample_sampletypeid'),
        ('StaticData', '0006_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='MaterialID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StaticData.material'),
        ),
        migrations.AddField(
            model_name='sample',
            name='StatusID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='StaticData.status'),
            preserve_default=False,
        ),
    ]
