# Generated by Django 5.1 on 2024-09-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Samples', '0006_sample_materialid_sample_statusid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='MaterialID',
        ),
        migrations.AlterField(
            model_name='sample',
            name='StatusID',
            field=models.IntegerField(),
        ),
    ]
