# Generated by Django 5.1 on 2024-09-02 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Samples', '0007_remove_sample_materialid_alter_sample_statusid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='SampleTypeID',
            new_name='SampleType',
        ),
    ]
