# Generated by Django 5.1 on 2024-09-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Samples', '0008_rename_sampletypeid_sample_sampletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='SampleType',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
