# Generated by Django 5.1 on 2024-09-02 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Samples', '0009_alter_sample_sampletype'),
        ('StaticData', '0006_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='SampleType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StaticData.sampletype'),
        ),
    ]
