# Generated by Django 5.1 on 2024-09-02 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Samples', '0011_sample_material'),
        ('StaticData', '0006_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='StatusID',
        ),
        migrations.AddField(
            model_name='sample',
            name='Status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='StaticData.status'),
            preserve_default=False,
        ),
    ]
