# Generated by Django 5.1 on 2024-09-03 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Samples', '0012_remove_sample_statusid_sample_status'),
        ('StaticData', '0006_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(blank=True, max_length=100, null=True)),
                ('Sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Samples.sample')),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StaticData.test')),
                ('UOM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StaticData.uom')),
            ],
        ),
    ]
