# Generated by Django 5.1 on 2024-09-12 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Samples', '0013_sampleresult'),
        ('StaticData', '0007_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='Event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='StaticData.event'),
            preserve_default=False,
        ),
    ]
